<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_login_user</name>
   <tag></tag>
   <elementGuidId>9e530b26-c493-44cd-b1fd-7d286faa0306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bdffa31-284f-4410-9654-ffa2e5662077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e91b821e-a561-4d09-a610-d882cbee6684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat email anda</value>
      <webElementGuid>1205e2ee-6ba3-4089-b41b-e14f87a37b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_user</value>
      <webElementGuid>8734923f-1f39-44a1-a6c8-be97cd700c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_user&quot;)</value>
      <webElementGuid>797e1ed4-6196-4edf-980e-030a6a0bd1a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_user']</value>
      <webElementGuid>c4bef46b-cee1-4458-a78a-06bd2367207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/p/input</value>
      <webElementGuid>2d06080e-9814-4fb3-bc0a-6e151bcce17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dc06b31a-19c5-42ba-a318-3a795d9feb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan alamat email anda' and @id = 'login_user']</value>
      <webElementGuid>0702640d-e1b9-4f91-a07a-e8f51af17397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
